i3companion: Catch errors while trying to notify of errors
I hit a key while logging in and caused this - my guess is a
notification tried to spawn dunst via dbus service, while dunst was
already in the process of starting up itself. This was the error:

DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process
/usr/bin/dunst exited with status 1